Childminder applicant disq
InformedSolutions/OFS-MORE-Childminder-Website pull request #720
Opened 2021-11-23 12:58 UTC by witoldpiecewicz

## Description

Finished all the tasks for Suitability questions:
- views
- templates
- forms
- tests
- updated task_list

## Todo's before PR

- [ ] Branch has been rebased against develop
- [ ] Unit tests passed (`make test`)
- [ ] PR named appropriately - see [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Commits-guideline)
- [ ] PR description describes the overall goals of PR commits
- [ ] Templates have been checked against the relevant user-story

## Migrations

- [ ] Null fields in models specifies default value
- [ ] You generated and applied migrations (`make migrate`)
- [ ] You updated fixtures (`make export`)

## PR Todo's

Please refer to PR [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-submit-a-pull-request)

- [ ] Specified reviewers (even if it's yourself)
- [ ] Specified assignees (those who'll merge)
- [ ] Specified labels

## PR review

Please refer to PR review [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-review-a-pull_request)

- [ ] Code syntax formatting checked
- [ ] Debug messages are absent

## PR merge

Select only one:

- [ ] Should be merged?
- [ ] Should be rebased?
- [ ] Should be squashed?

Please refer to PR merge [guide](https://github.com/InformedSolutions/OFS-MORE-DevOps-Tooling/wiki/Pull-requests#how-to-merge-a-pull_request)

2021-11-24 10:37 UTC, jenniferbrown94 requested changes

2021-11-24 10:37 UTC, jenniferbrown94 commented on application/models/suitability.py
> +
Can you add in the timelog fields method? You'll see this in other models, every field except the application_id should be included in the timelog

2021-11-24 11:02 UTC, witoldpiecewicz commented on application/models/suitability.py
> +
Done

2021-11-24 11:13 UTC, jenniferbrown94 commented
I'm happy with this PR now - I will approve once we are ready to merge

2021-11-25 11:12 UTC, jenniferbrown94 commented
Hi @witoldpiecewicz, @nitz14 - there is an item in the https://jira.informed.com/browse/ODQ-42 to remove the existing social services question - this is at the end of the people in the home section and should be removed from the journey and any summary pages.

2021-11-25 15:24 UTC, witoldpiecewicz commented
@jenniferbrown94 it has been removed

2021-11-25 15:51 UTC, jenniferbrown94 commented
rerun jenkins build

2021-11-26 13:14 UTC, witoldpiecewicz commented
@jenniferbrown94 the issues with visual alignment have been resolved

2021-12-01 14:28 UTC, jenniferbrown94 commented
rerun jenkins build

2021-12-01 15:02 UTC, jenniferbrown94 commented
rerun jenkins build

2021-12-02 10:22 UTC, jenniferbrown94 approved these changes

2021-12-02 10:22 UTC, merged