Feat/oyah 111/add master summary page to personal questions
InformedSolutions/OFS-MORE-Childminder-Website pull request #796
Opened 2022-03-09 17:35 UTC by CharlieWilkening

All buttons working, OYAH-113 on a separate branch in the end and not quite finished so will be on a separate

2022-03-09 17:37 UTC, jenniferbrown94 commented
rerun jenkins build

2022-03-09 17:38 UTC, AustenCWells approved these changes

2022-03-09 17:40 UTC, jenniferbrown94 requested changes

2022-03-09 17:40 UTC, jenniferbrown94 commented on application/templates/bad-link.html
> +<p>The link we sent you can only be used once. TEST</p>
Can you remove this please?

2022-03-09 17:40 UTC, jenniferbrown94 commented on application/views/other_people_health_check/master_summary_page_temp.py
> +import logging
do you need both views?

2022-03-10 09:40 UTC, jenniferbrown94 commented
rerun jenkins build

2022-03-10 10:00 UTC, CharlieWilkening commented on application/views/other_people_health_check/master_summary_page_temp.py
> +import logging
Removed in most recent commit

2022-03-10 11:19 UTC, jenniferbrown94 commented
closing this, because your other pr included all this changes anyway

2022-03-10 11:19 UTC, closed without merging